### ISSUE TITLE
browser friendly status code data

### ISSUE THREAD

**Issue by smhg** [moll/js-standard-http-error#1]
I wanted to use **standard-http-error** to throw client side errors (using browserify).
After minification however, this library adds about 80Kb to my build.

I didn't test this thoroughly, but it's almost certain it's due to the dependency [http-codes](https://github.com/flesler/node-http-codes), which requires node's `http` module to list HTTP status codes.
I guess that approach has a lot benefits, but it makes this basically node-only.

Would you be open for a dependency change to broaden the use of this library?
I did a bit of research and these options seem to be equally defendable:
- [http-status](https://github.com/wdavidw/node-http-status): exports only status code data (source not mentioned).
- [statuses](https://github.com/jshttp/statuses): exports data with some utility methods, but also provides direct access to IANA data.

If so, do you have a preference? If you want, I'll prepare a PR.

**Comment by moll** [comment]
Hey, absolutely! Thanks for taking the time to do research!

I took the liberty of just caching the output of `Http.STATUS_CODES` in `codes.json` and directing Browserify to use that. The bundle's now the bare minimum with no dependencies besides [StandardError.js](https://github.com/moll/js-standard-error). I released the change as v1.1.0 seconds ago.

Let me know if that works for you. Thanks again!

**Comment by moll** [comment]
PS. You can test what gets bundled with:

``` sh
browserify index.js
```

**Comment by smhg** [comment]
Great! Thank you!

**Comment by moll** [comment]
You might want to upgrade to v1.1.1 as it now sets the `name` property on the prototype, too.
v1.1.0 didn't, so when you minifiy code for browsers, you might end up with a mangled constructor name and therefore incorrect `toString` behavior. ;-)
