### ISSUE TITLE
HTTP 522 label

### ISSUE THREAD

**Issue by antoinerousseau** [moll/js-standard-http-error#3]
Could we add this one? I can make a PR.
https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522-Connection-timed-out

**Comment by moll** [comment]
Hey!

I'm not sure this is an actual standardized error code. Could it just be Cloudflare's own invention for what 502 Bad Gateway is?

**Comment by antoinerousseau** [comment]
It's indeed CloudFlare-specific, it's just that when I create a new instance I get and undefined error message in this case.
```js
const error = new HttpError(522);
console.log(error.message); // undefined
```

**Comment by antoinerousseau** [comment]
Fyi I'm solving this by adding the `statusText` in the frontend use of the lib.
```js
throw new HttpError(response.status, response.statusText)
```

**Comment by moll** [comment]
That's a good way to set a custom message. Are you happy to continue doing that? As for the `undefined` message, that seems expected for unknown messages. I can't think of a better way to handle them either...

Btw, if you want to throw errors from Fetch requests, you may find https://github.com/moll/js-fetch-throw to be valuable. It does exactly what you're doing above.
